language: php

sudo: false

php:
    - 5.6
    - 7.0

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    - composer install --prefer-dist

script:
    - php vendor/bin/phpunit

